### PR TITLE
added `use_default_if_value_is_blank` option

### PR DESCRIPTION
**Pull request by studio3104**
i added `use_default_if_value_is_blank` option.
apply default value when this option is set even if value is blank string (even if value is not `nil`)

please check :)

### CODE REVIEW

**Comment by tagomoris** [comment]
`default` is the option for replacement of something missing.
So `use_default_if_value_is_blank` is bad name and doesn't describe correct meaning.

I think that your requirement seems something like `substitute_for_blank`.
(And strings only with spaces should be tested.)

**Comment by sonots** [comment]
What about `default: 'foo', use_default_if: proc_object`?

Another idea is `default: 'foo', blank_if: proc_object`, but I felt the former is more descriptive.

**Comment by sonots** [comment]
@tagomoris 

> substitute_for_blank

Does this mean a default value for blank value (I mean `blank` here like ActiveSupport's `blank?`)?
Or, a definition of a string which will be treated as a string?

If it means the former, I have -1 because I think users do not want to write two default values for nil and `String#blank?`

**Comment by tagomoris** [comment]
@sonots This validator has a validation definition named as `not_blank`.

**Comment by studio3104** [comment]
@tagomoris do you think which is better? or neither?
i think the latter is better
- add `substitute_for_blank` option
  - allowed string value
  - specify substitute value in case value is blank
- add `substitute_default_for_blank` option
  - allowed bool value
  - substitute value specified in `default` option for value if value is blank string when this option is true

**Comment by tagomoris** [comment]
`substitute_for_blank` is better because it allows users to use different string between missing and blank value.

**Comment by studio3104** [comment]
hmm... really...?
user must specify same word twice if it is not desired...
is there really user who want to use  properly...?

**Comment by studio3104** [comment]
does not change your opinion...?

**Comment by tagomoris** [comment]
Do you think that there's so big difference between these 2 lines?
- `substitute_for_blank: "BLANK"`
- `substitute_default_for_blank: true`

With the former pattern, we have an option to use different value for `blank` value from `default`.

**Comment by studio3104** [comment]
yes, i think there is a big difference
if we choice a way like you said, user have to write codes like below even if user does not want to use two types of default values properly

``` ruby
default: 'hoge',
substitute_for_blank: 'hoge',
```

i think it is so needlessly implementation...

**Comment by tagomoris** [comment]
you can use variables or consts whether you wants.

**Comment by studio3104** [comment]
hmm... you're totally correct...
but i feel specifying same words twice is not a good, even if the value is a variable

**Comment by studio3104** [comment]
alright, i could understand your opinion in detailed
i will re-create PR as following your way
thanks :)

ref: http://twitter.com/tagomoris/status/621348508042293248

**Pull request closed without merging**
